### ISSUE TITLE
Kamelet tutorial have a wrong expression

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto.io#118]
When following this tutorial https://kaoto.io/workshop/intermediate-kamelet/#solution-3, it seems the extraction part is not working properly:

```yaml
        - setBody:
            expression:
              simple:
                expression: $.text
```

it should be:

```
        - setBody:
            expression:
              simple:
                expression: "${body[text]}"
```
